name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '42 8 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t pyactioncheck .

    - name: Use image to run Python program and check app versions to verify installation
      run: |
        pwd
        docker run --rm --name versioncheck -v /home/runner/work/pyaction/pyaction:/pyaction -w /pyaction pyactioncheck python version-check/versions.py 

    - name: Create Pull Request
      if: ${{ github.event_name != 'pull_request' }}
      uses: peter-evans/create-pull-request@v7.0.7
      with:
        title: "Automated update"
        commit-message: "Updated versions.json and changelog.md"
        author: Vincent A. Cicirello <cicirello@users.noreply.github.com>
        committer: Vincent A. Cicirello <cicirello@users.noreply.github.com>
        delete-branch: true
